import { create } from 'zustand'
import type { ApiAppVersion } from '@/shared/lib/api'

// ── Console Store ────────────────────────────────────────────────────────────

type LogLevel = 'info' | 'warn' | 'error' | 'success'

export interface ConsoleEntry {
  id: number
  timestamp: number
  level: LogLevel
  source: string
  message: string
  detail?: unknown
}

let entryId = 0

interface ConsoleState {
  entries: ConsoleEntry[]
  log: (level: LogLevel, source: string, message: string, detail?: unknown) => void
  clear: () => void
}

export const useConsoleStore = create<ConsoleState>()((set) => ({
  entries: [],

  log: (level, source, message, detail) => {
    set((state) => ({
      entries: [
        ...state.entries.slice(-199), // keep last 200
        {
          id: ++entryId,
          timestamp: Date.now(),
          level,
          source,
          message,
          detail,
        },
      ],
    }))
  },

  clear: () => {
    set({ entries: [] })
  },
}))

// ── App Document Store ───────────────────────────────────────────────────────

interface AppDocumentState {
  /** TSX source code generated by the LLM */
  sourceCode: string | null
  /** Current version info from the backend */
  currentVersion: ApiAppVersion | null

  /** Set new source code */
  setSourceCode: (source: string) => void
  setCurrentVersion: (version: ApiAppVersion | null) => void
  reset: () => void
}

export const useAppDocumentStore = create<AppDocumentState>()((set) => ({
  sourceCode: null,
  currentVersion: null,

  setSourceCode: (source) => {
    set({ sourceCode: source })
  },

  setCurrentVersion: (version) => {
    set({ currentVersion: version })
  },

  reset: () => {
    set({ sourceCode: null, currentVersion: null })
  },
}))
